# CMake generated Testfile for 
# Source directory: D:/PROGRAMS/devtools-course-practice/modules/fraction
# Build directory: D:/PROGRAMS/devtools-course-practice/iv.kiselev/modules/fraction
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(fraction_can_Run "D:/PROGRAMS/devtools-course-practice/iv.kiselev/bin/fraction.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(fraction_can_Run "D:/PROGRAMS/devtools-course-practice/iv.kiselev/bin/fraction.exe")
else()
  add_test(fraction_can_Run NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(fraction_can_Print_Help_Without_Arguments "D:/PROGRAMS/devtools-course-practice/iv.kiselev/bin/fraction.exe")
  set_tests_properties(fraction_can_Print_Help_Without_Arguments PROPERTIES  PASS_REGULAR_EXPRESSION "This is a fraction calculator application")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(fraction_can_Print_Help_Without_Arguments "D:/PROGRAMS/devtools-course-practice/iv.kiselev/bin/fraction.exe")
  set_tests_properties(fraction_can_Print_Help_Without_Arguments PROPERTIES  PASS_REGULAR_EXPRESSION "This is a fraction calculator application")
else()
  add_test(fraction_can_Print_Help_Without_Arguments NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(fraction_can_Check_Number_Of_Arguments "D:/PROGRAMS/devtools-course-practice/iv.kiselev/bin/fraction.exe" "1")
  set_tests_properties(fraction_can_Check_Number_Of_Arguments PROPERTIES  PASS_REGULAR_EXPRESSION "ERROR: Should be 3 arguments.")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(fraction_can_Check_Number_Of_Arguments "D:/PROGRAMS/devtools-course-practice/iv.kiselev/bin/fraction.exe" "1")
  set_tests_properties(fraction_can_Check_Number_Of_Arguments PROPERTIES  PASS_REGULAR_EXPRESSION "ERROR: Should be 3 arguments.")
else()
  add_test(fraction_can_Check_Number_Of_Arguments NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(fraction_can_Detect_Wrong_Number_Format "D:/PROGRAMS/devtools-course-practice/iv.kiselev/bin/fraction.exe" "te1d" "+" "3")
  set_tests_properties(fraction_can_Detect_Wrong_Number_Format PROPERTIES  PASS_REGULAR_EXPRESSION "Wrong number format!")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(fraction_can_Detect_Wrong_Number_Format "D:/PROGRAMS/devtools-course-practice/iv.kiselev/bin/fraction.exe" "te1d" "+" "3")
  set_tests_properties(fraction_can_Detect_Wrong_Number_Format PROPERTIES  PASS_REGULAR_EXPRESSION "Wrong number format!")
else()
  add_test(fraction_can_Detect_Wrong_Number_Format NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(fraction_can_Detect_Wrong_Operation_Format "D:/PROGRAMS/devtools-course-practice/iv.kiselev/bin/fraction.exe" "1/2" "d2d" "2/3")
  set_tests_properties(fraction_can_Detect_Wrong_Operation_Format PROPERTIES  PASS_REGULAR_EXPRESSION "Wrong operation format!")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(fraction_can_Detect_Wrong_Operation_Format "D:/PROGRAMS/devtools-course-practice/iv.kiselev/bin/fraction.exe" "1/2" "d2d" "2/3")
  set_tests_properties(fraction_can_Detect_Wrong_Operation_Format PROPERTIES  PASS_REGULAR_EXPRESSION "Wrong operation format!")
else()
  add_test(fraction_can_Detect_Wrong_Operation_Format NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(fraction_can_Add_Fractions "D:/PROGRAMS/devtools-course-practice/iv.kiselev/bin/fraction.exe" "6/7" "+" "1")
  set_tests_properties(fraction_can_Add_Fractions PROPERTIES  PASS_REGULAR_EXPRESSION "13/7")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(fraction_can_Add_Fractions "D:/PROGRAMS/devtools-course-practice/iv.kiselev/bin/fraction.exe" "6/7" "+" "1")
  set_tests_properties(fraction_can_Add_Fractions PROPERTIES  PASS_REGULAR_EXPRESSION "13/7")
else()
  add_test(fraction_can_Add_Fractions NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(fraction_can_Diff_Fractions "D:/PROGRAMS/devtools-course-practice/iv.kiselev/bin/fraction.exe" "3/2" "-" "2/5")
  set_tests_properties(fraction_can_Diff_Fractions PROPERTIES  PASS_REGULAR_EXPRESSION "11/10")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(fraction_can_Diff_Fractions "D:/PROGRAMS/devtools-course-practice/iv.kiselev/bin/fraction.exe" "3/2" "-" "2/5")
  set_tests_properties(fraction_can_Diff_Fractions PROPERTIES  PASS_REGULAR_EXPRESSION "11/10")
else()
  add_test(fraction_can_Diff_Fractions NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(fraction_can_Mult_Fractions "D:/PROGRAMS/devtools-course-practice/iv.kiselev/bin/fraction.exe" "-17/2" "*" "-3/5")
  set_tests_properties(fraction_can_Mult_Fractions PROPERTIES  PASS_REGULAR_EXPRESSION "51/10")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(fraction_can_Mult_Fractions "D:/PROGRAMS/devtools-course-practice/iv.kiselev/bin/fraction.exe" "-17/2" "*" "-3/5")
  set_tests_properties(fraction_can_Mult_Fractions PROPERTIES  PASS_REGULAR_EXPRESSION "51/10")
else()
  add_test(fraction_can_Mult_Fractions NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(fraction_can_Divide_Fractions "D:/PROGRAMS/devtools-course-practice/iv.kiselev/bin/fraction.exe" "8/3" "/" "2/5")
  set_tests_properties(fraction_can_Divide_Fractions PROPERTIES  PASS_REGULAR_EXPRESSION "20/3")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(fraction_can_Divide_Fractions "D:/PROGRAMS/devtools-course-practice/iv.kiselev/bin/fraction.exe" "8/3" "/" "2/5")
  set_tests_properties(fraction_can_Divide_Fractions PROPERTIES  PASS_REGULAR_EXPRESSION "20/3")
else()
  add_test(fraction_can_Divide_Fractions NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(fraction_can_Detect_Divide_By_Zero "D:/PROGRAMS/devtools-course-practice/iv.kiselev/bin/fraction.exe" "12/5" "/" "0")
  set_tests_properties(fraction_can_Detect_Divide_By_Zero PROPERTIES  PASS_REGULAR_EXPRESSION "Can't divide by zero")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(fraction_can_Detect_Divide_By_Zero "D:/PROGRAMS/devtools-course-practice/iv.kiselev/bin/fraction.exe" "12/5" "/" "0")
  set_tests_properties(fraction_can_Detect_Divide_By_Zero PROPERTIES  PASS_REGULAR_EXPRESSION "Can't divide by zero")
else()
  add_test(fraction_can_Detect_Divide_By_Zero NOT_AVAILABLE)
endif()
subdirs("src")
subdirs("test")
subdirs("application")
